import React, { useState } from "react";
import ReactMarkdown from "react-markdown";
import { PenTool, Loader2 } from "lucide-react";
import { generateResponse } from "../api";

const CreativeMode = () => {
  const [prompt, setPrompt] = useState("");
  const [content, setContent] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleCreate = async () => {
    if (!prompt.trim() || isLoading) return;

    setIsLoading(true);
    // Don't clear content immediately to allow reference, or maybe clear it?
    // Let's clear it for a fresh start as it's "Creative Mode" usually implies generating a piece.
    setContent("");

    try {
      console.log("Sending request to OpenAI with:", {
        mode: "creative",
        prompt,
      });
      const response = await generateResponse("creative", prompt);
      console.log("Received response:", response);
      setContent(response);
    } catch (error) {
      console.error("Error in CreativeMode:", error);
      setContent(
        `Error: ${
          error.message || "Unknown error occurred. Check console for details."
        }`
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full bg-linear-to-br from-amber-50 via-orange-50 to-rose-50">
      <div className="border-b border-orange-200/50 p-3 sm:p-6 bg-white/70 backdrop-blur-sm shadow-sm">
        <div className="max-w-5xl mx-auto w-full flex flex-col sm:flex-row gap-3 sm:gap-4">
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Write a story about... compose a poem on..."
            className="flex-1 p-3 sm:p-4 rounded-xl sm:rounded-2xl border-2 border-orange-200 focus:ring-2 focus:ring-orange-500 focus:border-transparent font-serif text-base sm:text-lg shadow-sm bg-white transition-all"
            onKeyDown={(e) => e.key === "Enter" && handleCreate()}
          />
          <button
            onClick={handleCreate}
            disabled={isLoading || !prompt.trim()}
            className="bg-linear-to-r from-orange-600 to-rose-600 text-white px-6 sm:px-8 py-3 rounded-xl sm:rounded-2xl hover:shadow-xl hover:scale-105 transition-all disabled:opacity-50 disabled:hover:scale-100 font-semibold flex items-center justify-center gap-2 shadow-lg shadow-orange-500/30 text-base sm:text-lg"
          >
            {isLoading ? (
              <>
                <Loader2 className="animate-spin" size={20} />
                <span className="hidden sm:inline">Writing...</span>
                <span className="sm:hidden">Writing...</span>
              </>
            ) : (
              <>
                <PenTool size={20} className="sm:w-[22px] sm:h-[22px]" />
                <span>Create</span>
              </>
            )}
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        <div className="max-w-4xl mx-auto w-full py-8 sm:py-16 px-4 sm:px-10 min-h-full">
          {content ? (
            <article className="bg-white/90 backdrop-blur-sm rounded-2xl sm:rounded-3xl shadow-2xl border border-orange-100 p-6 sm:p-12 animate-in fade-in slide-in-from-bottom-8 duration-700">
              <div className="prose prose-sm sm:prose-xl prose-stone max-w-none font-serif prose-headings:font-bold prose-headings:text-gray-800 prose-p:text-gray-700 prose-p:leading-relaxed prose-a:text-orange-600 prose-strong:text-gray-900">
                <ReactMarkdown>{content}</ReactMarkdown>
              </div>
              <div className="mt-8 sm:mt-12 pt-6 sm:pt-8 border-t border-orange-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 sm:gap-0">
                <div className="flex items-center gap-2 text-xs sm:text-sm text-gray-500">
                  <PenTool size={14} className="sm:w-4 sm:h-4" />
                  <span>Generated by MiniGPT</span>
                </div>
                <div className="text-xs text-gray-400 font-mono">
                  {new Date().toLocaleDateString()}
                </div>
              </div>
            </article>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-center space-y-6 sm:space-y-8 px-4">
              <div className="relative">
                <div className="absolute inset-0 bg-orange-200 blur-3xl opacity-30 rounded-full"></div>
                <div className="relative w-24 h-24 sm:w-32 sm:h-32 bg-white rounded-2xl sm:rounded-3xl flex items-center justify-center shadow-2xl border border-orange-200">
                  <PenTool
                    size={48}
                    className="sm:w-16 sm:h-16 text-orange-600"
                  />
                </div>
              </div>
              <div className="space-y-2 sm:space-y-3">
                <h3 className="text-2xl sm:text-3xl font-bold text-gray-800 font-serif">
                  Your Creative Canvas Awaits
                </h3>
                <p className="text-base sm:text-lg text-gray-600 font-serif italic max-w-md px-4">
                  Let your imagination flow. I'll craft stories, poems, and
                  prose that captivate.
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CreativeMode;
